#!/usr/bin/env ruby

require_relative "lib/code.rb"

arg = ARGV.first

if Dir.exists?(arg)
  Code::Application.start(arg)
elsif File.exists?(arg)
  Code.eval(File.read(arg))
else
  Code.eval(arg)
end
